-- Copyright (c) 2020 Snowflake Inc. All rights reserved.
-- There is no SQL to run for this step (yet) until listings can be created with SQL, but you can visit the documentation page below to walk through your listing creation:
-- https://docs.snowflake.com/en/user-guide/marketplace-managing-data-listings.html